module.exports = {
  pageAccessToken: "EAAKOoRO0eWgBAKLeeZAr3GO06ggHjnjCxsOsbkBPkCgNPcykOg0TQOKHizeLuGc2ul7vghYAEwbvhcuMIfWVLImJ68oH9CoeIoistETH70MIDzv2icDhbs0HCuqEe7rnYQiEsl8MXbBmonMeSMxg3c7unDWkujZATVADTHOAZDZD",
  verifyToken: "fuckyouappengine",
};